grocery_app/models.py
from sqlalchemy_utils import URLType
from grocery_app.extensions import db
from grocery_app.utils import FormEnum
from flask_login import UserMixin


class ItemCategory(FormEnum):
    """Categories of grocery items."""
    PRODUCE = 'Produce'
    DELI = 'Deli'
    BAKERY = 'Bakery'
    PANTRY = 'Pantry'
    FROZEN = 'Frozen'
    OTHER = 'Other'


class GroceryStore(db.Model):
    """Grocery Store model."""

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    address = db.Column(db.String(200), nullable=False)
    items = db.relationship("GroceryItem", back_populates="store")
    created_by_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    created_by = db.relationship("User")

    def __str__(self):
        return f"<Store: {self.title}>"

    def __repr__(self):
        return f"<Store: {self.title}>"


class GroceryItem(db.Model):
    """Grocery Item model."""

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    price = db.Column(db.Float(precision=2), nullable=False)
    category = db.Column(db.Enum(ItemCategory), default=ItemCategory.OTHER)
    photo_url = db.Column(URLType)
    store_id = db.Column(db.Integer, db.ForeignKey("grocery_store.id"), nullable=False)
    store = db.relationship("GroceryStore", back_populates="items")
    created_by_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    created_by = db.relationship("User")
    users_shopping_list = db.relationship(
        "User",
        secondary="shopping_list_items_table",
        back_populates="shopping_list_items",
    )


    def __str__(self):
        return f"<Item: {self.name}>"

    def __repr__(self):
        return f"<Item: {self.name}>"


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    shopping_list_items = db.relationship(
        "GroceryItem",
        secondary="shopping_list_items_table",
        back_populates="users_shopping_list",
    )

    def __repr__(self):
        return f"<User: {self.username}>"


shopping_list_items_table = db.Table(
    "shopping_list_items_table",
    db.Column("user_id", db.Integer, db.ForeignKey("user.id")),
    db.Column("grocery_item_id", db.Integer, db.ForeignKey("grocery_item.id")),
)

grocery_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    DateField,
    SelectField,
    SubmitField,
    FloatField,
    PasswordField,
)

from wtforms.validators import DataRequired, Length, URL, optional
from grocery_app.models import ItemCategory, GroceryStore


class GroceryStoreForm(FlaskForm):
    """Form for adding/updating a GroceryStore."""

    title = StringField(
        "Store Title", validators=[DataRequired(), Length(min=3, max=80)]
    )
    address = StringField(
        "Store Address", validators=[DataRequired(), Length(min=3, max=200)]
    )
    submit = SubmitField("Submit")


class GroceryItemForm(FlaskForm):
    """Form for adding/updating a GroceryItem."""

    name = StringField("Item Name", validators=[DataRequired(), Length(min=3, max=80)])
    price = FloatField("Item Price", validators=[DataRequired()])
    category = SelectField("Category", choices=ItemCategory.choices())
    photo_url = StringField("Item Photo URL", validators=[URL(require_tld=True)])
    store = SelectField("Stores", query_factory=lambda: GroceryStore.query)
    submit = SubmitField("Submit")

grocery_app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from grocery_app.models import GroceryStore, GroceryItem, User
from grocery_app.main.forms import GroceryStoreForm, GroceryItemForm

from grocery_app.extensions import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################


@main.route("/")
def homepage():
    all_stores = GroceryStore.query.all()
    print(all_stores)
    return render_template("home.html", all_stores=all_stores)


@main.route("/new_store", methods=["GET", "POST"])
@login_required
def new_store():
    form = GroceryStoreForm()
    if form.validate_on_submit():
        new_store = GroceryStore(
            title=form.title.data, address=form.address.data, created_by=current_user
        )
        db.session.add(new_store)
        db.session.commit()
        flash("New store was created successfully.")
        return redirect(url_for("main.store_detail", store_id=new_store.id))
    return render_template("new_store.html", form=form)


@main.route("/new_item", methods=["GET", "POST"])
@login_required
def new_item():
    form = GroceryItemForm()
    if form.validate_on_submit():
        new_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data,
            created_by=current_user,
        )
        db.session.add(new_item)
        db.session.commit()
        flash("New Item was created successfully.")
        return redirect(url_for("main.item_detail", item_id=new_item.id))

    return render_template("new_item.html", form=form)


@main.route("/store/<store_id>", methods=["GET", "POST"])
@login_required
def store_detail(store_id):
    store = GroceryStore.query.get(store_id)
    form = GroceryStoreForm(obj=store)
    if form.validate_on_submit():
        store.title = form.title.data
        store.address = form.address.data
        db.session.add(store)
        db.session.commit()
        flash("Store was updated successfully.")
        return redirect(url_for("main.store_detail", store_id=store_id))

    return render_template("store_detail.html", store=store, form=form)


@main.route("/item/<item_id>", methods=["GET", "POST"])
@login_required
def item_detail(item_id):
    item = GroceryItem.query.get(item_id)
    form = GroceryItemForm(obj=item)
    if form.validate_on_submit():
        item.name = form.name.data
        item.price = form.price.data
        item.category = form.category.data
        item.photo_url = form.photo_url.data
        item.store = form.store.data
        db.session.add(item)
        db.session.commit()
        flash("Item was updated successfully.")
        return redirect(url_for("main.item_detail", item_id=item_id))
    return render_template("item_detail.html", item=item, form=form)


@main.route("/add_to_shopping_list/<item_id>", methods=["POST"])
@login_required
def add_to_shopping_list(item_id):
    item = GroceryItem.query.get(item_id)
    current_user.shopping_list_items.append(item)
    db.session.add(current_user)
    db.session.commit()
    shopping_list_items = current_user.shopping_list_items
    return render_template("shoppinglist.html", shopping_list_items=shopping_list_items)


@main.route("/shopping_list")
@login_required
def shopping_list():
    shopping_list_items = current_user.shopping_list_items
    return render_template("shoppinglist.html", shopping_list_items=shopping_list_items)

grocery_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                    {% if current_user.is_authenticated %}
                        <a href="/new_store">New Store</a>
                        <a href="/new_item">New Item</a>
                        <a href="/shopping_list">Shopping List</a>
                    {% else %}
                        <a href="/signup">Sign Up</a>
                        <a href="/login">Log In</a>
                    {% endif %}   
                </div>
            </nav>
            {% if current_user.is_authenticated %}
                <p>You are logged in as {{ current_user.username }}</p>
            {% endif %}
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>The best place to track prices and find the hottest deals!</em></p>

<h2>All Stores</h2>

{% for store in all_stores %}
<div class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item - {{ item.name }}</h1>

<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>

<p><strong>Created By:</strong> {{ current_user.username }}</p>

{% if current_user.is_authenticated %}
    <form action="/add_to_shopping_list/{{ item.id }}" method="POST">
        <input type="submit" value="Add to List">
    </form>
{% endif %} 

<h2>Edit Item</h2>

<form method="POST" action="{{ url_for('main.item_detail', item_id=item.id) }}">
    <fieldset>
        <legend>Please enter your information:</legend>
        {{ form.name.label }}
        {{ form.name }}
        {{ form.price.label }}
        {{ form.price }}
        {{ form.category.label }}
        {{ form.category }}
        {{ form.photo_url.label }}
        {{ form.photo_url }}
        {{ form.store.label }}
        {{ form.store }}
        <input type="submit" value="Submit">
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST" action="{{url_for('main.new_item')}}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
            {{ form.name.label }}
            {{ form.name }}
            {{ form.price.label }}
            {{ form.price }}
            {{ form.category.label }}
            {{ form.category }}
            {{ form.photo_url.label }}
            {{ form.photo_url }}
            {{ form.store.label }}
            {{ form.store }}
        <input type="submit" value="Submit">
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form method="POST" action="{{ url_for('main.new_store') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
            {{ form.title.label }}
            {{ form.title }}
            {{ form.address.label }}
            {{ form.address }}
            {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/shoppinglist.html
{% extends 'base.html' %}
{% block content %}

<h1>Shopping List</h1>

{% for item in current_user.shopping_list_items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}

{% endblock %}

grocery_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
  {{ form.csrf_token }}
  <fieldset>
      {{ form.username.label }}
      {{ form.username }}
      <ul>
      {% for error in form.username.errors %}
          <li class="error">{{ error }}</li>
      {% endfor %}
      </ul>

      {{ form.password.label }}
      {{ form.password }}
      <ul>
      {% for error in form.password.errors %}
          <li class="error">{{ error }}</li>
      {% endfor %}
      </ul>

      {{ form.submit }}
  </fieldset>
</form>

{% endblock %}

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>

<strong>Address:</strong> {{ store.address }}

<p><strong>Created By:</strong> {{ current_user.username }}</p>

<h2>Items</h2>

<div class="items">
    {% for item in store.items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Store</h2>

<form method="POST" action="{{ url_for('main.store_detail', store_id=store.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
        {{ form.title.label }}
        {{ form.title }}
        {{ form.address.label }}
        {{ form.address }}
        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}